In [1]:
import pandas as pd
import numpy as np

In [3]:
test = pd.read_csv("../test.csv")

In [13]:
test.pivot_table(index="Trap", columns="Species", aggfunc=len, values="Id")

Species,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX
Trap,,,,,,,,
T001,95,95,95,95,95,95,95,95
T002,95,103,161,118,95,95,95,95
T002A,95,95,95,95,95,95,95,95
T002B,95,95,95,95,95,95,95,95
T003,95,95,113,97,95,95,95,95
T004,95,95,95,95,95,95,95,95
T005,95,95,95,95,95,95,95,95
T006,95,95,95,95,95,95,95,95
T007,95,95,95,95,95,95,95,95
T008,95,96,150,101,95,95,95,95
T009,190,191,195,192,190,190,190,190
T011,95,100,134,105,95,95,95,95
T012,95,97,105,104,95,95,95,95
T013,95,95,104,95,95,95,95,95
T014,95,95,97,95,95,95,95,95
T015,95,95,95,95,95,95,95,95
T016,95,95,110,95,95,95,95,95
T017,95,95,95,95,95,95,95,95
T018,95,95,95,95,95,95,95,95
T019,95,95,95,95,95,95,95,95
T025,95,95,95,95,95,95,95,95
T027,95,95,134,99,95,95,95,95
T028,95,95,113,100,95,95,95,95
T030,95,95,101,100,95,95,95,95
T031,95,95,98,95,95,95,95,95
T033,95,95,97,95,95,95,95,95
T034,95,95,95,95,95,95,95,95
T035,190,190,190,190,190,190,190,190
T036,95,95,95,95,95,95,95,95
T037,95,95,95,95,95,95,95,95
...,...,...,...,...,...,...,...,...
T206,95,95,95,95,95,95,95,95
T209,95,95,98,95,95,95,95,95
T212,95,95,106,97,95,95,95,95
T215,95,95,95,95,95,95,95,95
T218,95,95,100,97,95,95,95,95
T218A,95,95,95,95,95,95,95,95
T218B,95,95,97,95,95,95,95,95
T218C,95,95,97,95,95,95,95,95
T219,95,95,95,95,95,95,95,95
T220,95,95,111,95,95,95,95,95
T221,95,95,104,95,95,95,95,95
T222,95,95,96,96,95,95,95,95
T223,95,96,103,100,95,95,95,95
T224,95,95,96,95,95,95,95,95
T225,95,95,101,95,95,95,95,95
T226,95,95,95,95,95,95,95,95
T227,95,95,96,96,95,95,95,95
T228,95,95,98,96,95,95,95,95
T229,95,95,95,95,95,95,95,95
T230,95,95,97,95,95,95,95,95
T231,95,95,115,96,95,95,95,95
T232,95,95,95,95,95,95,95,95
T233,95,95,100,95,95,95,95,95
T234,95,95,95,95,95,95,95,95
T235,95,95,96,95,95,95,95,95
T236,95,95,98,95,95,95,95,95
T237,95,95,95,95,95,95,95,95
T238,95,95,95,95,95,95,95,95
T900,95,234,455,288,105,97,99,95
T903,95,99,112,98,95,95,95,95

In [7]:
test.Species.unique()

array(['CULEX PIPIENS/RESTUANS', 'CULEX RESTUANS', 'CULEX PIPIENS',
       'CULEX SALINARIUS', 'CULEX TERRITANS', 'CULEX TARSALIS',
       'UNSPECIFIED CULEX', 'CULEX ERRATICUS'], dtype=object)

In [15]:
train = pd.read_csv("../train.csv")

In [18]:
train.pivot_table(index="Trap", columns="Species", aggfunc=len, values='Date')

Species,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS
Trap,,,,,,,
T001,NaN,6,8,NaN,NaN,NaN,1
T002,NaN,41,83,59,1,NaN,1
T003,NaN,26,60,34,1,NaN,1
T004,NaN,5,5,2,NaN,NaN,NaN
T005,NaN,5,8,NaN,NaN,NaN,1
T006,NaN,7,10,7,NaN,NaN,NaN
T007,NaN,9,10,4,NaN,NaN,NaN
T008,NaN,28,70,40,1,NaN,NaN
T009,NaN,23,51,36,NaN,NaN,1
T011,NaN,28,63,40,1,NaN,1
T012,NaN,19,56,29,1,NaN,NaN
T013,NaN,20,57,26,NaN,NaN,1
T014,NaN,11,12,6,NaN,NaN,1
T015,NaN,10,13,12,NaN,NaN,NaN
T016,NaN,18,29,18,NaN,NaN,1
T017,NaN,10,42,23,2,1,NaN
T018,NaN,4,33,23,1,NaN,2
T019,NaN,8,10,5,NaN,NaN,NaN
T025,NaN,10,14,3,NaN,NaN,NaN
T027,NaN,16,39,25,1,NaN,12
T028,NaN,22,52,42,1,NaN,NaN
T030,NaN,26,57,40,NaN,1,2
T031,NaN,32,64,42,NaN,NaN,8
T033,NaN,21,51,23,1,NaN,1
T034,NaN,7,7,1,1,NaN,1
T035,NaN,16,32,21,NaN,NaN,3
T036,NaN,9,10,4,1,NaN,NaN
T037,NaN,12,13,3,NaN,NaN,1
T039,NaN,17,43,18,1,NaN,1
T040,NaN,NaN,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...
T160,NaN,22,43,23,1,NaN,2
T161,NaN,8,13,5,NaN,NaN,NaN
T162,NaN,10,10,1,NaN,NaN,NaN
T200,NaN,36,53,22,2,1,15
T206,NaN,9,10,1,NaN,NaN,1
T209,NaN,33,51,38,NaN,1,7
T212,NaN,34,66,36,2,NaN,14
T215,NaN,14,18,3,3,NaN,7
T218,NaN,16,35,23,NaN,NaN,NaN
T219,NaN,8,9,4,NaN,NaN,NaN
T220,NaN,19,48,29,NaN,NaN,2
T221,NaN,27,54,27,3,NaN,1
T222,NaN,9,32,18,NaN,NaN,1
T223,NaN,13,45,27,NaN,NaN,2
T224,NaN,7,28,19,NaN,NaN,NaN
T225,NaN,17,50,35,1,NaN,NaN
T226,NaN,16,31,28,1,NaN,1
T227,NaN,13,36,29,NaN,NaN,NaN
T228,NaN,7,28,24,NaN,NaN,3
T229,NaN,1,6,1,NaN,NaN,NaN
T230,NaN,10,32,21,NaN,NaN,2
T231,NaN,8,22,12,NaN,NaN,NaN
T232,NaN,4,24,22,NaN,NaN,NaN
T233,NaN,13,25,12,NaN,NaN,NaN
T235,NaN,16,26,15,1,NaN,4
T236,NaN,6,17,10,NaN,NaN,NaN
T237,NaN,NaN,3,NaN,NaN,NaN,NaN
T238,NaN,1,3,2,NaN,NaN,1
T900,1,131,362,243,11,NaN,2
T903,NaN,31,65,44,NaN,NaN,NaN