#Predict mosquitos dayswise (groupby date -.-)
because if we don't, we have data points that are exactly the same except that the numMosquitos is different, which HAS to fuck up the classifier.

## load and prepare data

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn import cross_validation, preprocessing, metrics

In [2]:
df_train = pd.read_csv('aggregated_train_with_nummosquitos.csv')# from make_aggregated_with_Nummosquitos
#df_test = pd.read_csv('../test_filled_new.csv')
#orig = pd.read_csv('../test_filled_new.csv')
df_test = pd.read_csv('../test_filled_new.csv')

### encode species and trap, set unspecified to mix, drop strings

In [3]:
df_train['counter'] = 1

In [4]:
X = df_train.copy()

In [5]:
string_features = ['Address','Street','AddressNumberAndStreet','CodeSum']
species_encoder = preprocessing.LabelEncoder()
trap_encoder = preprocessing.LabelEncoder()
#X_dump = X[string_features]
df_dump = df_test[string_features]
#X_dump = X[string_features]

df_test.Species[df_test.Species == 'UNSPECIFIED CULEX'] = 'CULEX PIPIENS/RESTUANS'
#X.Species = species_encoder.fit_transform(X.Species)
y = df_train['NumMosquitos']
#df_test.Species = species_encoder.transform(df_test.Species)
#df_train.Species = species_encoder.transform(df_train.Species)

/home/thomas/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

### groupby date

In [6]:
tmp  = X.groupby(['Date','Trap']).sum()

In [7]:
tmp.WnvPresent.max(), X.WnvPresent.max()

(12, 1)

In [8]:
tmp.NumMosquitos.max(), X.NumMosquitos.max()

(3002, 50)

either:

1. disregard species and only predict num mosquitos independently

2. predict number mosquitos per species (make new variable for each species or it won't fit in the dates!). In this case we also need to store information about in how many '50 sets' there was Wnvpresent.

In [9]:
count_species = X.groupby(['Date','Species']).sum()['counter']

In [10]:
count_2 = count_species.reset_index()

In [11]:
count_2.head()

         Date                 Species  counter
0  2007-05-29           CULEX PIPIENS        1
1  2007-05-29  CULEX PIPIENS/RESTUANS        9
2  2007-05-29          CULEX RESTUANS       15
3  2007-06-05           CULEX PIPIENS        5
4  2007-06-05  CULEX PIPIENS/RESTUANS       20

In [12]:
len(count_2)

378

In [ ]:
tmp = []
for species in count_2.Species.values:
    for date in count_2.Date.values:
        mask_species = X.Species ==species
        mask_date = X.Date == date
        mask = mask_species & mask_date #all(mask_species, mask_date)
        mask_count_date = count_2.Date == date 
        mask_count_species = count_2.Species == species
        mask_count = mask_count_species & mask_count_date
        #print(mask)
        #print(len(mask_count))
        #print(len(count_2))
        #print(count_2[mask_count])
        X[species]= 0
        X[species][mask] = count_2.counter[mask_count]
        tmp.append(count_2.counter[mask_count])
    #X.ix[(X.Species == species, X.Date == date).all(),species] = -1

In [ ]:
count_2.set_index(['Date','Species'])
X.set_index(['Date','Species'])

In [77]:
X = X.fillna(0)

In [78]:
len(X)

10506

In [79]:
X

,Unnamed: 0,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,...,23_week_avrgTavg,counter,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TERRITANS,CULEX TARSALIS,CULEX ERRATICUS,species
0,0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,...,63.275862,1,0,-1,0,0,0,0,0,-1
1,1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,...,63.275862,1,0,0,-1,0,0,0,0,-1
2,2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,...,63.275862,1,0,0,-1,0,0,0,0,-1
3,3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,...,63.275862,1,0,-1,0,0,0,0,0,-1
4,4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,...,63.275862,1,0,0,-1,0,0,0,0,-1
5,5,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX PIPIENS/RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,...,63.275862,1,0,-1,0,0,0,0,0,-1
6,6,2007-05-29,"7500 North Oakley Avenue, Chicago, IL 60645, USA",CULEX PIPIENS/RESTUANS,75,N OAKLEY AVE,T148,"7500 N OAKLEY AVE, Chicago, IL",42.017430,-87.687769,...,63.275862,1,0,-1,0,0,0,0,0,-1
7,7,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,...,64.428571,1,0,0,-1,0,0,0,0,-1
8,8,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,...,64.428571,1,0,0,-1,0,0,0,0,-1
9,9,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,...,64.428571,1,0,-1,0,0,0,0,0,-1
10,10,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,...,64.428571,1,0,0,-1,0,0,0,0,-1
11,11,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,...,64.428571,1,0,0,-1,0,0,0,0,-1
12,12,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX PIPIENS/RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,...,64.428571,1,0,-1,0,0,0,0,0,-1
13,13,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,...,64.428571,1,0,-1,0,0,0,0,0,-1
14,14,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,...,64.428571,1,0,0,-1,0,0,0,0,-1
15,15,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,...,64.428571,1,0,-1,0,0,0,0,0,-1
16,16,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,...,64.428571,1,0,0,-1,0,0,0,0,-1
17,17,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",CULEX RESTUANS,11,S PEORIA ST,T091,"1100 S PEORIA ST, Chicago, IL",41.862292,-87.648860,...,64.428571,1,0,0,-1,0,0,0,0,-1
18,18,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",CULEX RESTUANS,17,W 95TH ST,T094,"1700 W 95TH ST, Chicago, IL",41.720848,-87.666014,...,64.428571,1,0,0,-1,0,0,0,0,-1
19,19,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,...,64.428571,1,0,0,-1,0,0,0,0,-1
20,20,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,...,64.428571,1,-1,0,0,0,0,0,0,-1
21,21,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX PIPIENS/RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,...,64.428571,1,0,-1,0,0,0,0,0,-1
22,22,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,...,64.428571,1,0,0,-1,0,0,0,0,-1
23,23,2007-05-29,"1500 North Long Avenue, Chicago, IL 60651, USA",CULEX RESTUANS,15,N LONG AVE,T153,"1500 N LONG AVE, Chicago, IL",41.907645,-87.760886,...,64.428571,1,0,0,-1,0,0,0,0,-1
24,24,2007-05-29,"8900 South Carpenter Street, Chicago, IL 60620...",CULEX RESTUANS,89,S CARPENTER ST,T159,"8900 S CARPENTER ST, Chicago, IL",41.732984,-87.649642,...,64.428571,1,0,0,-1,0,0,0,0,-1
25,25,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,...,64.500000,1,0,-1,0,0,0,0,0,-1
26,26,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,...,64.500000,1,0,0,-1,0,0,0,0,-1
27,27,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,...,64.500000,1,-1,0,0,0,0,0,0,-1
28,28,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,...,64.500000,1,0,-1,0,0,0,0,0,-1
29,29,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,...,64.500000,1,0,0,-1,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,10476,2013-09-26,"3700 South Pulaski Road, Chicago, IL 60623, USA",CULEX PIPIENS,37,S PULASKI RD,T063,"3700 S PULASKI RD, Chicago, IL",41.825610,-87.726549,...,70.442177,1,-1,0,0,0,0,0,0,-1
10477,10477,2013-09-26,"South Doty Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,12,S DOTY AVE,T115,"1200 S DOTY AVE, Chicago, IL",41.673408,-87.599862,...,70.442177,1,0,-1,0,0,0,0,0,-1
10478,10478,2013-09-26,"South Doty Avenue, Chicago, IL, USA",CULEX PIPIENS,12,S DOTY AVE,T115,"1200 S DOTY AVE, Chicago, IL",41.673408,-87.599862,...,70.442177,1,-1,0,0,0,0,0,0,-1
10479,10479,2013-09-26,"South Stony Island Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,10,S STONY ISLAND AVE,T138,"1000 S STONY ISLAND AVE, Chicago, IL",41.726465,-87.585413,...,70.442177,1,0,-1,0,0,0,0,0,-1
10480,10480,2013-09-26,"South Stony Island Avenue, Chicago, IL, USA",CULEX PIPIENS,10,S STONY ISLAND AVE,T138,"1000 S STONY ISLAND AVE, Chicago, IL",41.726465,-87.585413,...,70.442177,1,-1,0,0,0,0,0,0,-1
10481,10481,2013-09-26,"South Brandon Avenue, Chicago, IL 60617, USA",CULEX PIPIENS/RESTUANS,13,S BRANDON,T209,"1300 S BRANDON, Chicago, IL",41.740641,-87.546587,...,70.442177,1,0,-1,0,0,0,0,0,-1
10482,10482,2013-09-26,"South Brandon Avenue, Chicago, IL 60617, USA",CULEX RESTUANS,13,S BRANDON,T209,"1300 S BRANDON, Chicago, IL",41.740641,-87.546587,...,70.442177,1,0,0,-1,0,0,0,0,-1
10483,10483,2013-09-26,"South Brandon Avenue, Chicago, IL 60617, USA",CULEX PIPIENS,13,S BRANDON,T209,"1300 S BRANDON, Chicago, IL",41.740641,-87.546587,...,70.442177,1,-1,0,0,0,0,0,0,-1
10484,10484,2013-09-26,"3700 118th Street, Chicago, IL 60617, USA",CULEX PIPIENS/RESTUANS,37,E 118TH ST,T212,"3700 E 118TH ST, Chicago, IL",41.680946,-87.535198,...,70.442177,1,0,-1,0,0,0,0,0,-1
10485,10485,2013-09-26,"3700 118th Street, Chicago, IL 60617, USA",CULEX PIPIENS,37,E 118TH ST,T212,"3700 E 118TH ST, Chicago, IL",41.680946,-87.535198,...,70.442177,1,-1,0,0,0,0,0,0,-1
10486,10486,2013-09-26,"2400 East 105th Street, Chicago, IL 60617, USA",CULEX PIPIENS/RESTUANS,24,E 105TH ST,T128,"2400 E 105TH ST, Chicago, IL",41.704572,-87.565666,...,70.442177,1,0,-1,0,0,0,0,0,-1
10487,10487,2013-09-26,"2400 East 105th Street, Chicago, IL 60617, USA",CULEX PIPIENS,24,E 105TH ST,T128,"2400 E 105TH ST, Chicago, IL",41.704572,-87.565666,...,70.442177,1,-1,0,0,0,0,0,0,-1
10488,10488,2013-09-26,"8900 South Muskegon Avenue, Chicago, IL 60617,...",CULEX PIPIENS/RESTUANS,89,S MUSKEGON AVE,T099,"8900 S MUSKEGON AVE, Chicago, IL",41.733643,-87.555510,...,70.442177,1,0,-1,0,0,0,0,0,-1
10489,10489,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,...,70.442177,1,0,-1,0,0,0,0,0,-1
10490,10490,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,...,70.442177,1,0,0,-1,0,0,0,0,-1
10491,10491,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,...,70.442177,1,-1,0,0,0,0,0,0,-1
10492,10492,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS/RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,...,70.442177,1,0,-1,0,0,0,0,0,-1
10493,10493,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,...,70.442177,1,0,0,-1,0,0,0,0,-1
10494,10494,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,...,70.442177,1,-1,0,0,0,0,0,0,-1
10495,10495,2013-09-26,"4800 West Montana Street, Chicago, IL 60639, USA",CULEX PIPIENS/RESTUANS,48,W MONTANA ST,T222,"4800 W MONTANA ST, Chicago, IL",41.925198,-87.746381,...,70.442177,1,0,-1,0,0,0,0,0,-1
10496,10496,2013-09-26,"8200 South Kostner Avenue, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,82,S KOSTNER AVE,T225,"8200 S KOSTNER AVE, Chicago, IL",41.743402,-87.731435,...,70.442177,1,0,-1,0,0,0,0,0,-1
10497,10497,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,...,70.442177,1,0,-1,0,0,0,0,0,-1
10498,10498,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,...,70.442177,1,-1,0,0,0,0,0,0,-1
10499,10499,2013-09-26,"1700 West Addison Street, Chicago, IL 60613, USA",CULEX PIPIENS/RESTUANS,17,W ADDISON ST,T224,"1700 W ADDISON ST, Chicago, IL",41.947227,-87.671457,...,70.442177,1,0,-1,0,0,0,0,0,-1
10500,10500,2013-09-26,"West Garfield Boulevard, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,90,W GARFIELD BLVD,T226,"9000 W GARFIELD BLVD, Chicago, IL",41.793818,-87.654234,...,70.442177,1,0,-1,0,0,0,0,0,-1
10501,10501,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS/RESTUANS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,...,70.442177,1,0,-1,0,0,0,0,0,-1
10502,10502,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,...,70.442177,1,-1,0,0,0,0,0,0,-1
10503,10503,2013-09-26,"5100 West 72nd Street, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 72ND ST,T035,"5100 W 72ND ST, Chicago, IL",41.763733,-87.742302,...,70.442177,1,0,-1,0,0,0,0,0,-1
10504,10504,2013-09-26,"1700 North Ashland Avenue, Chicago, IL 60622, USA",CULEX PIPIENS/RESTUANS,17,N ASHLAND AVE,T232,"1700 N ASHLAND AVE, Chicago, IL",41.912563,-87.668055,...,70.442177,1,0,-1,0,0,0,0,0,-1
10505,10505,2013-09-26,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX PIPIENS/RESTUANS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,...,70.442177,1,0,-1,0,0,0,0,0,-1