In [40]:
import pandas as pd
import numpy as np
from sklearn import cross_validation, preprocessing, metrics
df_train = pd.read_csv('new_train.csv')
train_support = pd.read_csv('../train.csv')

df_test = pd.read_csv('new_test.csv')
test_support = pd.read_csv('../test.csv')

In [41]:
df_train['Date'] = train_support.Date
df_train['Trap'] = train_support.Trap

In [42]:
df_train.head()

,Unnamed: 0,Id,Species,Block,Latitude,Longitude,AddressAccuracy,WnvPresent,Station,Tmax,...,20_week_avrgTavg,21_week_avrgPrecipTotal,21_week_avrgTavg,22_week_avrgPrecipTotal,22_week_avrgTavg,23_week_avrgPrecipTotal,23_week_avrgTavg,count_mosquitos,Date,Trap
0,0,0,CULEX PIPIENS/RESTUANS,41,41.954690,-87.800991,9,0,1,88,...,63.275862,0.062586,63.275862,0.062586,63.275862,0.062586,63.275862,1,2007-05-29,T002
1,1,1,CULEX RESTUANS,41,41.954690,-87.800991,9,0,1,88,...,63.275862,0.062586,63.275862,0.062586,63.275862,0.062586,63.275862,1,2007-05-29,T002
2,2,2,CULEX RESTUANS,62,41.994991,-87.769279,9,0,1,88,...,63.275862,0.062586,63.275862,0.062586,63.275862,0.062586,63.275862,1,2007-05-29,T007
3,3,3,CULEX PIPIENS/RESTUANS,79,41.974089,-87.824812,8,0,1,88,...,63.275862,0.062586,63.275862,0.062586,63.275862,0.062586,63.275862,1,2007-05-29,T015
4,4,4,CULEX RESTUANS,79,41.974089,-87.824812,8,0,1,88,...,63.275862,0.062586,63.275862,0.062586,63.275862,0.062586,63.275862,4,2007-05-29,T015

In [43]:
groups = ['Date','Trap','Species']
df_train = df_train.join(df_train.groupby(groups)['WnvPresent'].sum(), on=groups,rsuffix  = '_mean' )

In [46]:
(df_train.WnvPresent_mean == df_train.WnvPresent).all()

False

In [47]:
len(df_train)

10506

In [48]:
len(df_train.drop_duplicates())

10506

In [21]:
df_train.to_csv('new_train.csv',index=['Id'])

In [22]:
df_test.to_csv('new_test.csv',index=['Id'])

In [49]:
for species in df_train.Species.values:
    df_train[species] = df_train.count_mosquitos

In [50]:
df_train

,Unnamed: 0,Id,Species,Block,Latitude,Longitude,AddressAccuracy,WnvPresent,Station,Tmax,...,Date,Trap,WnvPresent_mean,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX PIPIENS,CULEX SALINARIUS,CULEX TERRITANS,CULEX TARSALIS,CULEX ERRATICUS
0,0,0,CULEX PIPIENS/RESTUANS,41,41.954690,-87.800991,9,0,1,88,...,2007-05-29,T002,0,1,1,1,1,1,1,1
1,1,1,CULEX RESTUANS,41,41.954690,-87.800991,9,0,1,88,...,2007-05-29,T002,0,1,1,1,1,1,1,1
2,2,2,CULEX RESTUANS,62,41.994991,-87.769279,9,0,1,88,...,2007-05-29,T007,0,1,1,1,1,1,1,1
3,3,3,CULEX PIPIENS/RESTUANS,79,41.974089,-87.824812,8,0,1,88,...,2007-05-29,T015,0,1,1,1,1,1,1,1
4,4,4,CULEX RESTUANS,79,41.974089,-87.824812,8,0,1,88,...,2007-05-29,T015,0,4,4,4,4,4,4,4
5,5,5,CULEX PIPIENS/RESTUANS,65,41.999129,-87.795585,8,0,1,88,...,2007-05-29,T045,0,2,2,2,2,2,2,2
6,6,6,CULEX PIPIENS/RESTUANS,75,42.017430,-87.687769,8,0,1,88,...,2007-05-29,T046,0,1,1,1,1,1,1,1
7,7,7,CULEX RESTUANS,15,41.921600,-87.666455,8,0,2,88,...,2007-05-29,T048,0,1,1,1,1,1,1,1
8,8,8,CULEX RESTUANS,25,41.891118,-87.654491,8,0,2,88,...,2007-05-29,T048,0,2,2,2,2,2,2,2
9,9,9,CULEX PIPIENS/RESTUANS,11,41.867108,-87.654224,8,0,2,88,...,2007-05-29,T049,0,1,1,1,1,1,1,1
10,10,10,CULEX RESTUANS,11,41.867108,-87.654224,8,0,2,88,...,2007-05-29,T050,0,1,1,1,1,1,1,1
11,11,11,CULEX RESTUANS,11,41.896282,-87.655232,8,0,2,88,...,2007-05-29,T054,0,2,2,2,2,2,2,2
12,12,12,CULEX PIPIENS/RESTUANS,21,41.919343,-87.694259,8,0,2,88,...,2007-05-29,T054,0,3,3,3,3,3,3,3
13,13,13,CULEX PIPIENS/RESTUANS,22,41.921965,-87.632085,8,0,2,88,...,2007-05-29,T086,0,1,1,1,1,1,1,1
14,14,14,CULEX RESTUANS,22,41.921965,-87.632085,8,0,2,88,...,2007-05-29,T086,0,1,1,1,1,1,1,1
15,15,15,CULEX PIPIENS/RESTUANS,22,41.688324,-87.676709,8,0,2,88,...,2007-05-29,T091,0,1,1,1,1,1,1,1
16,16,16,CULEX RESTUANS,22,41.688324,-87.676709,8,0,2,88,...,2007-05-29,T094,0,3,3,3,3,3,3,3
17,17,17,CULEX RESTUANS,11,41.862292,-87.648860,8,0,2,88,...,2007-05-29,T096,0,5,5,5,5,5,5,5
18,18,18,CULEX RESTUANS,17,41.720848,-87.666014,9,0,2,88,...,2007-05-29,T096,0,1,1,1,1,1,1,1
19,19,19,CULEX RESTUANS,22,41.731922,-87.677512,8,0,2,88,...,2007-05-29,T129,0,1,1,1,1,1,1,1
20,20,20,CULEX PIPIENS,22,41.731922,-87.677512,8,0,2,88,...,2007-05-29,T129,0,2,2,2,2,2,2,2
21,21,21,CULEX PIPIENS/RESTUANS,53,41.891126,-87.611560,5,0,2,88,...,2007-05-29,T143,0,1,1,1,1,1,1,1
22,22,22,CULEX RESTUANS,53,41.891126,-87.611560,5,0,2,88,...,2007-05-29,T148,0,1,1,1,1,1,1,1
23,23,23,CULEX RESTUANS,15,41.907645,-87.760886,8,0,2,88,...,2007-05-29,T153,0,1,1,1,1,1,1,1
24,24,24,CULEX RESTUANS,89,41.732984,-87.649642,8,0,2,88,...,2007-05-29,T159,0,1,1,1,1,1,1,1
25,25,25,CULEX PIPIENS/RESTUANS,41,41.954690,-87.800991,9,0,1,64,...,2007-06-05,T002,0,3,3,3,3,3,3,3
26,26,26,CULEX RESTUANS,41,41.954690,-87.800991,9,0,1,64,...,2007-06-05,T002,0,5,5,5,5,5,5,5
27,27,27,CULEX PIPIENS,41,41.954690,-87.800991,9,0,1,64,...,2007-06-05,T002,0,1,1,1,1,1,1,1
28,28,28,CULEX PIPIENS/RESTUANS,79,41.974089,-87.824812,8,0,1,64,...,2007-06-05,T015,0,1,1,1,1,1,1,1
29,29,29,CULEX RESTUANS,79,41.974089,-87.824812,8,0,1,64,...,2007-06-05,T015,0,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,10476,10476,CULEX PIPIENS,37,41.825610,-87.726549,9,0,2,75,...,2013-09-26,T102,0,2,2,2,2,2,2,2
10477,10477,10477,CULEX PIPIENS/RESTUANS,12,41.673408,-87.599862,5,0,2,75,...,2013-09-26,T102,0,1,1,1,1,1,1,1
10478,10478,10478,CULEX PIPIENS,12,41.673408,-87.599862,5,0,2,75,...,2013-09-26,T102,0,1,1,1,1,1,1,1
10479,10479,10479,CULEX PIPIENS/RESTUANS,10,41.726465,-87.585413,5,0,2,75,...,2013-09-26,T027,0,5,5,5,5,5,5,5
10480,10480,10480,CULEX PIPIENS,10,41.726465,-87.585413,5,0,2,75,...,2013-09-26,T221,0,5,5,5,5,5,5,5
10481,10481,10481,CULEX PIPIENS/RESTUANS,13,41.740641,-87.546587,5,0,2,75,...,2013-09-26,T221,0,5,5,5,5,5,5,5
10482,10482,10482,CULEX RESTUANS,13,41.740641,-87.546587,5,0,2,75,...,2013-09-26,T221,0,4,4,4,4,4,4,4
10483,10483,10483,CULEX PIPIENS,13,41.740641,-87.546587,5,0,2,75,...,2013-09-26,T009,0,1,1,1,1,1,1,1
10484,10484,10484,CULEX PIPIENS/RESTUANS,37,41.680946,-87.535198,8,0,2,75,...,2013-09-26,T900,0,39,39,39,39,39,39,39
10485,10485,10485,CULEX PIPIENS,37,41.680946,-87.535198,8,0,2,75,...,2013-09-26,T900,0,4,4,4,4,4,4,4
10486,10486,10486,CULEX PIPIENS/RESTUANS,24,41.704572,-87.565666,8,0,2,75,...,2013-09-26,T900,0,16,16,16,16,16,16,16
10487,10487,10487,CULEX PIPIENS,24,41.704572,-87.565666,8,0,2,75,...,2013-09-26,T900,0,9,9,9,9,9,9,9
10488,10488,10488,CULEX PIPIENS/RESTUANS,89,41.733643,-87.555510,8,0,2,75,...,2013-09-26,T900,0,11,11,11,11,11,11,11
10489,10489,10489,CULEX PIPIENS/RESTUANS,10,41.750498,-87.605294,5,0,2,75,...,2013-09-26,T900,0,1,1,1,1,1,1,1
10490,10490,10490,CULEX RESTUANS,10,41.750498,-87.605294,5,0,2,75,...,2013-09-26,T222,0,1,1,1,1,1,1,1
10491,10491,10491,CULEX PIPIENS,10,41.750498,-87.605294,5,0,2,75,...,2013-09-26,T223,0,11,11,11,11,11,11,11
10492,10492,10492,CULEX PIPIENS/RESTUANS,40,41.659112,-87.538693,8,0,2,75,...,2013-09-26,T223,0,1,1,1,1,1,1,1
10493,10493,10493,CULEX RESTUANS,40,41.659112,-87.538693,8,0,2,75,...,2013-09-26,T225,0,3,3,3,3,3,3,3
10494,10494,10494,CULEX PIPIENS,40,41.659112,-87.538693,8,0,2,75,...,2013-09-26,T227,0,7,7,7,7,7,7,7
10495,10495,10495,CULEX PIPIENS/RESTUANS,48,41.925198,-87.746381,8,0,2,75,...,2013-09-26,T227,0,1,1,1,1,1,1,1
10496,10496,10496,CULEX PIPIENS/RESTUANS,82,41.743402,-87.731435,8,0,2,75,...,2013-09-26,T224,0,3,3,3,3,3,3,3
10497,10497,10497,CULEX PIPIENS/RESTUANS,65,41.728495,-87.600963,5,0,2,75,...,2013-09-26,T226,0,8,8,8,8,8,8,8
10498,10498,10498,CULEX PIPIENS,65,41.728495,-87.600963,5,0,2,75,...,2013-09-26,T230,0,13,13,13,13,13,13,13
10499,10499,10499,CULEX PIPIENS/RESTUANS,17,41.947227,-87.671457,9,0,2,75,...,2013-09-26,T230,0,5,5,5,5,5,5,5
10500,10500,10500,CULEX PIPIENS/RESTUANS,90,41.793818,-87.654234,5,0,2,75,...,2013-09-26,T228,0,3,3,3,3,3,3,3
10501,10501,10501,CULEX PIPIENS/RESTUANS,13,41.904194,-87.756155,9,0,2,75,...,2013-09-26,T035,0,6,6,6,6,6,6,6
10502,10502,10502,CULEX PIPIENS,13,41.904194,-87.756155,9,0,2,75,...,2013-09-26,T231,0,5,5,5,5,5,5,5
10503,10503,10503,CULEX PIPIENS/RESTUANS,51,41.763733,-87.742302,8,1,2,75,...,2013-09-26,T232,1,1,1,1,1,1,1,1
10504,10504,10504,CULEX PIPIENS/RESTUANS,17,41.912563,-87.668055,9,0,2,75,...,2013-09-26,T233,0,5,5,5,5,5,5,5
10505,10505,10505,CULEX PIPIENS/RESTUANS,42,41.776428,-87.627096,8,0,2,75,...,2013-09-26,T235,0,1,1,1,1,1,1,1